### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by breaup** [BloodMotion/Panel-AltisLife-GAMEWAVE#3]
Good day,

I downloaded the panel today and got it setup, I do get to the page and then it says Connexion. 

Connectez vous pour acceder au fonctionalite du panel. When I click it it redirects me to a 404 not found page since it cannot find /login. 

I moved the file off to the root of the apache directory and tried again and same. Checking the folder content I cannot find login folder either.

Any help?

**Comment by BloodMotion** [comment]
Hello, rewrite is active on your apache settings ?

Best regards.

**Comment by breaup** [comment]
root@YOSHI:/etc/apache2/sites-available# a2enmod rewrite
Module rewrite already enabled

<VirtualHost *:50>
        ServerAdmin email@email.com
DocumentRoot /var/www
        <Directory />
                Options FollowSymLinks
                AllowOverride FileInfo
                RewriteEngine On
                RewriteOptions Inherit
        </Directory>
        <Directory /var/www/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride FileInfo
                Order allow,deny
                allow from all
                RewriteEngine On
                RewriteOptions Inherit
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride FileInfo
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Order allow,deny
                Allow from all
                RewriteEngine On
                RewriteOptions Inherit
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

**Comment by breaup** [comment]
All right probly a caching issue in chrome. I loaded it in IE and it worked. well I got to the login page.
Cheers
