### ISSUE TITLE
Update Licenses Issue

### ISSUE THREAD

**Issue by mmaton** [BloodMotion/Panel-AltisLife-GAMEWAVE#4]
When trying to use add/delete licenses to a user on the modifier page i.e http://admin.gameserver.net/modifier?j=76561198196855935

I get the following error
POST http://admin.gameserver.net/ajax/update_licences.php 404 (Not Found)

This file is not included in the GIT repo

![screen shot 2015-05-20 at 23 37 18](https://cloud.githubusercontent.com/assets/982832/7738144/4e069708-ff49-11e4-90e5-7fb8666055a3.png)

**Comment by BloodMotion** [comment]
I've forgoten a file when I comit ... It's fix, check out "update_licences.php" on /ajax/ directory ;-)

**Comment by mmaton** [comment]
Thanks!
