### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by moreni57** [BloodMotion/Panel-AltisLife-GAMEWAVE#6]
Where are /login ?

it's my Panel installed i can't connect with this.

http://51.254.33.11/adminpanel/

**Comment by BloodMotion** [comment]
Are you sure you're using my dashboard (panel) ? I can see AltisLife RPG CONTROL at this URL -> http://tuk.fr/s/280815173048.png

**Comment by BloodMotion** [comment]
I'm closing this without any answer over since six months ... :+1:
