### ISSUE TITLE
https impossible ?

### ISSUE THREAD

**Issue by ImChip** [BloodMotion/Panel-AltisLife-GAMEWAVE#8]
Salut ,
J'ai récemment installé ton panel sur notre serveur mais je suis contré a un problème 
J'ai mon domaine sous https (https://admin.mondomain.tld)
J'ai un problème dans les listes joueurs http://prntscr.com/9j5zi9
En gros quand je clique sur la liste des gendarme 
J'ai la liste des joueur quand on se login sur le panel 
Et la liste que j'ai demandé 
J'ai déjà changé tous les http -> https mais sans succès 
Si tu as une solution je suis preneur 

Merci d'avance

**Comment by BloodMotion** [comment]
Le panel est tellement mal codé (premier projet quoi :D) que le protocole (http / https) influe sur le nombre de caractère total de l'URL qui est utilisé pour inclure ou non le champ de recherche ... Regarde dans **template.php** ligne **212** :
 
```php
$currentUrl = "http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
```

Remplace **http**:// par **https**:// ... Je pense que ça devrais régler ton souci :)

**Comment by ImChip** [comment]
Wep déjà merci de la réponse il est déjà assez cool comme sa :p 
J'ai fait des petites fonction perso pour whitelist les médic , les licences gendarme et tout :p 
Concernant la réponse que tu m'as donnée j'avais déjà tout remplace de http:// -> https:// dans le template.php 

Bref tout sa est fix ^^ 
Je me suis pas trop fait chier 
```
			<?php
			}
			if(Auth::isLogged()){
			$basicUrl = getcurrentpath();
			$currentUrl = $_SERVER['HTTPS_HOST'].$_SERVER['REQUEST_URI'];
			$location = $_SERVER['REQUEST_URI'];

			$urls= array('/');

			if (in_array($currentUrl,$urls)){
                            include 'content/liste.php';
			} else {

			}
			?>
```

**Comment by BloodMotion** [comment]
Pas de soucis, je clôture ;-) Un jour j'aurais la motive pour ré-ouvrir ce projet et le rendre + propre ! =D
